jobs:
  build:
    name: Build doyensec plugins on ${{ matrix.os }} using Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache Gradle resources
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Build Doyensec plugins
      run: ./doyensec/build_all.sh
    strategy:
      matrix:
        java:
        - 11
        os:
        - ubuntu-latest
        - macos-latest
name: doyensec-plugins-build
on:
  repository_dispatch:
    types: trigger-ga___doyensec-build.yml
